eth:
  node-url: http://localhost:8545
  test:
    private-key: 06e0f2a897cbbe5b5009c3d9cc1ee0b3d29e0d47b1d43125cf71918f24c4cb01
    auto-refill: 10
  gas-price: 1
  gas-limit: 2000000
channel:
  server:
    port: 8080
    endpoint-url: http://localhost:8080
  contracts:
    addresses:
#     make 'truffle migrate' and copy contract's addresses here
      ECRecovery: 0x1cd511e40139cae2b535eb52b3ed6e4784ec9fc6
      StandardToken: 0xd869c618c0da23dddc4c9c9bf70b5e457baae548
      ChannelLibrary: 0xef6da97a94b049aa11168f8b96b9bf75892d5834
      EndpointRegistry: 0x7040bd5616637c8a0eaf16e3c6641c1a6f7ee165
logging:
  level:
   default: INFO
#   org.apache.http: DEBUG
   papyrus: DEBUG