eth:
  rpc:
    node-url: http://localhost:8545
    gas-price: 1
    gas-limit: 2000000
channel:
  server:
    port: 8080
    health-check-port: 8081
cassandra:
  cluster: channel-node
  port: 9042
  contact-points: localhost
  delete-data: false
logging:
  level:
   default: INFO
#   org.apache.http: DEBUG
   papyrus: DEBUG