eth:
  rpc:
    node-url: http://localhost:8545
    gas-price: 1
    gas-limit: 2000000
  key:
    private-key: 06e0f2a897cbbe5b5009c3d9cc1ee0b3d29e0d47b1d43125cf71918f24c4cb01
    auto-refill: 10
channel:
  server:
    port: 8080
    endpoint-url: http://localhost:8080
  contracts:
    predeployed:
#     make 'truffle migrate' and copy contract's addresses here
      ECRecovery: 0x92904135d828e77fd0e612200e62323ef699b1a1
      StandardToken: 0xae514226df988d761c110d20c281110b5e969abd
      ChannelLibrary: 0x67e9cbbc278ecb39ad5f8beeddb7cad4df004242
      EndpointRegistry: 0x9788ff9ade8c0a0428f0d518fb0e56302b94fdc4
logging:
  level:
   default: INFO
#   org.apache.http: DEBUG
   papyrus: DEBUG