eth:
  rpc:
    node-url: http://localhost:8545
    gas-price: 1
    gas-limit: 2000000
  key:
    private-key: 06e0f2a897cbbe5b5009c3d9cc1ee0b3d29e0d47b1d43125cf71918f24c4cb01
    auto-refill: 10
channel:
  server:
    port: 8080
    endpoint-url: http://localhost:8080
  contracts:
#     make 'truffle migrate' and copy contract's addresses here
    predeployed:
      ECRecovery: 0x0876620f985b525b27a77440d9b879cc94df0600
      ChannelLibrary: 0x55b8e31492aa2a411fd3006dbb485ed086114ff5
      EndpointRegistry: 0x83647e5e8d9178dbb59b73fdc71604df7c29ad94
      PapyrusToken: 0x54fa4f9a0aa35013927fcba9b364d2b3ac7bdeff
      ChannelManager: 0xe76a3e4aeaaf72ca8c6d24da45af548c796fbf39
logging:
  level:
   default: INFO
#   org.apache.http: DEBUG
   papyrus: DEBUG