eth:
  rpc:
    node-url: http://localhost:8545
    gas-price: 1
    gas-limit: 2000000
channel:
  server:
    port: 8080
    health-check-port: 8081
logging:
  level:
   default: INFO
#   org.apache.http: DEBUG
   papyrus: DEBUG