eth:
  rpc:
    node-url: http://localhost:8545
    gas-price: 1
    gas-limit: 2000000
  key:
    private-key: 06e0f2a897cbbe5b5009c3d9cc1ee0b3d29e0d47b1d43125cf71918f24c4cb01
    auto-refill: 0.1
channel:
  server:
    port: 8080
    endpoint-url: http://localhost:8080
logging:
  level:
   default: INFO
#   org.apache.http: DEBUG
   papyrus: DEBUG